AY2425S1-CS2103-F12-1/tp

docs/_markbind/layouts/default.md, docs/site.json
Let's modify the necessary files in the docs folder to our own project specific names (InSUREance) to host on MarkBind generated project website
=> Configure markbind

docs/DeveloperGuide.md
As discussed, I have updated the NFRs as I have noted that this has not been worked on in PR #30. Thanks!
=> Update non functional requirements

README.md
Update and remove all the AB3 information with more project specific information.
fixes #19
=> Modify ReadMe.md

docs/DeveloperGuide.md
=> Add more glossary terms

docs/AboutUs.md
One of the links in AboutUs.md has not been updated and is currently not reflecting the image correctly. Lets update it so it works properly.
=> Update AboutUs.md to fix broken links

src/main/java/seedu/address/logic/commands/AddInsuranceCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java
Add AddInsuranceCommand and hook AddInsuranceCommand into the application
(no exception, no enhancement)
=> Barebones implementation of AddInsuranceCommand

src/main/java/seedu/address/model/person/insurance/InsurancePlans.java
InsurancePlans class is to support the addition of more than 1 insurance plans to Person class later on. This is because each client can purchase more than 1 insurance plan.
=> Add InsurancePlans class

src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteInsuranceCommandParser.java
Some minor javadocs issues and extra lines were modified. This makes the code neater.
Fixes #66
=> Fixed nits of PR#65 of team fork

src/main/java/seedu/address/logic/commands/AddInsuranceCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteInsuranceCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/insurance/InsurancePlan.java, src/main/java/seedu/address/model/person/insurance/InsurancePlanFactory.java, src/main/java/seedu/address/model/person/insurance/InsurancePlansManager.java, src/test/java/seedu/address/logic/commands/AddInsuranceCommandTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/insurance/InsurancePlanTest.java
Add basic functionality to AddInsurance Command
Merely placeholder methods exist on AddInsurance and does not change any data in the app itself.
Let's add actual execution steps inside of addInsurance so that it can change short term data for clients.
part of #52
=> Make insurance class useful

src/main/java/seedu/address/logic/commands/DeleteInsuranceCommand.java
Running "deleteInsurance..." allows added InsurancePlans to be deleted, however not reflected in PersonCard yet
=> Modify DeleteInsuranceCommand execute method to be useful

src/main/java/seedu/address/model/person/insurance/InsurancePlanFactory.java, src/test/java/seedu/address/model/person/insurance/InsurancePlanFactoryTest.java, src/test/java/seedu/address/model/person/insurance/InsurancePlanTest.java
There are no test cases to ensure the robustness of the insurance plan factory.
It becomes harder to catch regressive errors in future development work.
Let's add robust testing to the class to ensure that it works as intended in future.
This will help catch regression error faster and more efficiently.
=> Create Unit Tests for InsurancePlanFactory.java

src/main/java/seedu/address/logic/commands/ListClaimsCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/ListClaimsCommandParser.java, src/main/java/seedu/address/model/client/Client.java, src/main/java/seedu/address/model/client/insurance/InsurancePlansManager.java, src/main/java/seedu/address/model/client/insurance/claim/Claim.java
Create new fully-functional ListClaimsCommand and ListClaimsCommandParser to parse the new command `listClaims` to access a Client's claims.
=> List claims command

src/test/java/seedu/address/logic/commands/ListClaimsCommandTest.java, src/test/java/seedu/address/model/client/insurance/claim/ClaimTest.java
Add JUnit testing for Claim and ListClaimsCommand - ClaimTest and ListClaimsCommandTest
=> List claims command tests

src/test/java/seedu/address/logic/commands/AddInsuranceCommandTest.java, src/test/java/seedu/address/testutil/TypicalIndexes.java
Currently, we have no tests for AddInsuranceCommand.
Let's add tests for AddInsuranceCommand to increase our test coverage.
=> Add tests for AddInsuranceCommand

build.gradle, src/main/resources/view/MainWindow.fxml
A small change here to change the header at the top of the display
=> Change address app to InSUREance

src/test/java/seedu/address/logic/commands/DeleteClaimCommandTest.java
I forgot to add the most important part, the deletion from the expected model...
=> Fix the DeleteClaimCommandTest

src/test/java/seedu/address/logic/parser/DeleteInsuranceCommandParserTest.java
Currently, we have no tests for DeleteInsuranceCommandParser.
Let's add tests for DeleteInsuranceCommandParser to increase our test coverage.
=> Add DeleteInsuranceCommandParserTest.java

src/main/java/seedu/address/logic/commands/CloseClaimCommand.java, src/main/java/seedu/address/model/client/insurance/InsurancePlan.java, src/main/java/seedu/address/model/client/insurance/InsurancePlansManager.java, src/main/java/seedu/address/model/client/insurance/claim/ClaimComparator.java, src/test/java/seedu/address/logic/commands/CloseClaimCommandTest.java, src/test/java/seedu/address/model/client/insurance/InsurancePlansManagerTest.java, src/test/java/seedu/address/model/client/insurance/InvalidInsurancePlan.java, src/test/java/seedu/address/model/client/insurance/claim/ClaimStub.java
The test coverage for insurance plans manager object is quite low.
Lets add more tests to increase the code coverage and look for any
bugs.
=> Improve test coverage for insurance plans manager

src/test/java/seedu/address/logic/parser/AddInsuranceCommandParserTest.java
No tests were made for AddInsuranceCommandParser.
Let's add tests for AddInsuranceCommandParser to increase test coverage.
=> Add AddInsuranceCommandParserTest.java

docs/DeveloperGuide.md, docs/diagrams/ArchitectureSequenceDiagram.puml, docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/DeleteSequenceDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/StorageClassDiagram.puml, docs/diagrams/UiClassDiagram.puml
"Person" has already been refactored to "Client" in the rest of the codebase, but not in the UML diagrams. Let's refactor it too to reflect such changes 🙂
=> Refactor "Person" to "Client" in UML diagrams

src/main/java/seedu/address/logic/commands/AddClaimCommand.java, src/main/java/seedu/address/logic/commands/CloseClaimCommand.java, src/main/java/seedu/address/logic/commands/DeleteClaimCommand.java
Colons were missing in AddClaimCommand, CloseClaimCommand and DeleteClaimCommand which have been added
=> Add missing colons

docs/diagrams/add-claim/AddClaimSequenceDiagram-Logic.puml, docs/diagrams/add-insurance/AddInsuranceSequenceDiagram-Logic.puml
Let's add a sequence diagram for the implementation of add insurance to aid understanding.
=> Add UML sequence diagram for add insurance

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/client/insurance/InsurancePlansManager.java, src/main/java/seedu/address/model/client/insurance/claim/Claim.java
=> Update error message for duplicated Claim ID

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/client/insurance/claim/Claim.java
=> Add example to error message for invalid Claim ID

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/client/insurance/claim/Claim.java
=> Add new line character to AddCommand error message

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/parser/AddInsuranceCommandParser.java, src/main/java/seedu/address/logic/parser/DeleteInsuranceCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/client/insurance/InsurancePlanFactory.java, src/test/java/seedu/address/logic/commands/AddInsuranceCommandTest.java, src/test/java/seedu/address/logic/parser/AddInsuranceCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteClaimCommandParserTest.java, src/test/java/seedu/address/logic/parser/DeleteInsuranceCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/client/insurance/InsurancePlanFactoryTest.java
Addresses #164, #165, #172, #173
=> Standardising our Error Messages for AddInsurance and DeleteInsurance

docs/DeveloperGuide.md, docs/UserGuide.md
Updated target user profile to be for Singaporean users
Fixes #254
=> Update target user profile

docs/UserGuide.md
=> Change json file name to addressbook in DG

docs/DeveloperGuide.md
=> Removoe outdated Model diagram from DG for #258

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/add-claim/AddClaimSequenceDiagram-Logic.puml
Let's update the UG and DG to ensure consistent documentation and user guide for users.
Let's also include more planned enhancements such that it helps give some immunity during the PE.
Fix #277 ,
Fix #231 ,
Fix #214 .
=> Update DG and UG

docs/DeveloperGuide.md
Let's fix some inconsistent typos and numbering in the User Stories of the DG.
=> Update DG User stories

docs/UserGuide.md
Changed `inSUREance.jar` to `InSUREance.jar`
=> Fix typo in InSUREance
